### ISSUE TITLE
different output when running datalad run-procedure --discover

### ISSUE THREAD

**Issue by camiscaff** [LAAC-LSCP/datalad-procedures#4]
I got a different output when running datalad run-procedure --discover
I got this: 
```
cfg_yoda (/usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_yoda.py) [python_script]
cfg_text2git (/usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_text2git.py) [python_script]
cfg_metadatatypes (/usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_metadatatypes.py) [python_script]
```

**Comment by lucasgautheron** [comment]
What was the output of `python install.py` ?

Also, what do you get from `ls /usr/local/lib/python3.9/site-packages/datalad/resources/procedures/` ?

**Comment by camiscaff** [comment]
1. Output from ```python install.py```: 
```subdataset(ok): templates/el1000 (dataset)
cfg_yoda (/Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_yoda.py) [python_script]
cfg_noannex (/Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_noannex.py) [python_script]
cfg_text2git (/Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_text2git.py) [python_script]
cfg_metadatatypes (/Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_metadatatypes.py) [python_script]
subdataset(ok): templates/laac1 (dataset)
subdataset(ok): templates/laac2 (dataset)
copied procedures/cfg_laac1.py to /Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_laac1.py
copied procedures/cfg_el1000.py to /Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_el1000.py
copied procedures/cfg_laac2.py to /Users/cscaff/ChildProjectVenv/lib/python3.9/site-packages/datalad/resources/procedures/cfg_laac2.py
```

2. Output from ```ls /usr/local/lib/python3.9/site-packages/datalad/resources/procedures/```
```__pycache__		cfg_metadatatypes.py	cfg_text2git.py		cfg_yoda.py ```

3.

**Comment by camiscaff** [comment]
3. Error: 
```python: can't open file '/Users/cscaff/install.py': [Errno 2] No such file or director```

**Comment by lucasgautheron** [comment]
I see: there seems to be two installations of datalad mixed up. The script installs the procedure in the wrong location.

doing `python install.py --destination /usr/local/lib/python3.9/site-packages/datalad/resources/procedures` from the location of the `datalad-procedures` repository will work (make sure your working dir is datalad-procedures, otherwise you'll get the error that you got [here](https://github.com/LAAC-LSCP/datalad-procedures/issues/4#issuecomment-1029193615))

**Comment by camiscaff** [comment]
ok! thanks :)

If I do 3.  in ```datalad-procedures``` it gives this output:
```
copied procedures/cfg_laac1.py to /usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_laac1.py
copied procedures/cfg_el1000.py to /usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_el1000.py
copied procedures/cfg_laac2.py to /usr/local/lib/python3.9/site-packages/datalad/resources/procedures/cfg_laac2.py
```

**Comment by camiscaff** [comment]
and indeed now when I run ```datalad run-procedure --discover```
I got 
```
